### ISSUE TITLE
extension does not appear on menu

### ISSUE THREAD

**Issue by dandumit** [johnbeard/inkscape-label-guides#2]
Hello 
I would like to use this extension. I have copied files on all extension folders,  however does not appear on Inkscape menu.
I am on win10

Thank you,
Daniel

**Comment by johnbeard** [comment]
I'm not sure where extensions go on Windows. According to google it is `C:\Program Files\Inkscape\share\extensions`. You need the INX file and the Python file.

Do you need to restart inkscape?

**Comment by johnbeard** [comment]
Sorry, I cannot reproduce this. Please re-open if there are still issues.
