### ISSUE TITLE
Horizontal guides placed way above document area

### ISSUE THREAD

**Issue by Kilill** [johnbeard/inkscape-label-guides#5]
Inkscape 1.2.2 
If enabling guides. The horizontal guides are place a good way above the document
attaching a zip with a screenshot and a svg file of same
[LableGuides.zip](https://github.com/johnbeard/inkscape-label-guides/files/11361558/LableGuides.zip)

**Comment by johnbeard** [comment]
Interesting, looks like the deprecation note is wrong: should be viewbox, not view_port_!

Looks like it is working now:

![2023-04-30_173954_490x651_screenshot](https://user-images.githubusercontent.com/5386578/235365158-8b6b6448-8ef3-4df8-9d3d-b0dd595187a0.png)

**Comment by Kilill** [comment]
Yep!, works like a charm. 
Thanks for the very useful extension! ( and the quick fix as well)
